#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
    echo "You can't commit directly to $branch branch"
    exit 1
fi

git add .

if ! zlint --deny-warnings; then
    exit 1
fi

if ! zig build test; then
    exit 1
fi

