#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
    echo "You can't commit directly to $branch branch"
    exit 1
fi

git add .
zlint
if [[ $? != 0 ]]; then
    exit 1
fi
if [[ $? != 0 ]]; then
    zig build test
fi
